"""columns

Revision ID: 21fd6d8da83a
Revises: a9d362295412
Create Date: 2022-05-08 20:23:05.440767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21fd6d8da83a'
down_revision = 'a9d362295412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
