"""Added columns

Revision ID: 706a039af0e5
Revises: e9821c3ed403
Create Date: 2022-05-09 00:17:15.934082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706a039af0e5'
down_revision = 'e9821c3ed403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitch', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.drop_column('pitch', 'user_id')
    # ### end Alembic commands ###
