"""REFACTOR USER ID IN PITCH

Revision ID: c995a02b26fa
Revises: 37c923f9be4b
Create Date: 2022-05-09 13:37:13.143970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c995a02b26fa'
down_revision = '37c923f9be4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pitch', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('pitch_user_id_fkey', 'pitch', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('pitch_user_id_fkey', 'pitch', 'users', ['user_id'], ['id'])
    op.alter_column('pitch', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
