"""Added columns

Revision ID: e9821c3ed403
Revises: fd5698c8f438
Create Date: 2022-05-09 00:15:31.233565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9821c3ed403'
down_revision = 'fd5698c8f438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'commenttext',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('pitch', sa.Column('category', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'category')
    op.alter_column('comment', 'commenttext',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
