"""columns refactor

Revision ID: fd5698c8f438
Revises: a73451b63176
Create Date: 2022-05-08 20:53:18.684086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5698c8f438'
down_revision = 'a73451b63176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hashed', sa.String(length=128), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('users', 'password_hashed')
    # ### end Alembic commands ###
